export const TRAVEL_STYLES = [
  'solo',
  'couple',
  'family',
  'friends',
  'backpacker',
  'business',
  'luxury',
  'budget',
  'digital_nomad',
] as const;

export const TRAVEL_INTERESTS = [
  'food',
  'nature',
  'beaches',
  'shopping',
  'museums',
  'history',
  'theme_parks',
  'adventure',
  'hiking',
  'architecture',
  'photography',
  'culture',
  'nightlife',
  'coffee',
  'kids_activities',
  'family_activities',
  'religious_locations',
  'local_experiences',
] as const;

export const BUDGET_TIERS = [
  'backpacker',
  'budget',
  'mid_range',
  'premium',
  'luxury',
] as const;

export const TRANSPORT_PREFERENCES = [
  'walking',
  'train',
  'subway',
  'bus',
  'ferry',
  'taxi',
  'uber',
  'grab',
  'rental_car',
  'cycling',
] as const;

export const DIETARY_OPTIONS = [
  'none',
  'vegetarian',
  'vegan',
  'halal',
  'kosher',
  'gluten_free',
  'dairy_free',
  'nut_allergy',
] as const;

export const ACCESSIBILITY_OPTIONS = [
  'none',
  'wheelchair',
  'limited_mobility',
  'visual_assistance',
  'hearing_assistance',
  'elevator_required',
] as const;

export const WALKING_TOLERANCE = ['low', 'medium', 'high'] as const;

export const CURRENCIES = [
  'USD',
  'EUR',
  'GBP',
  'JPY',
  'PHP',
  'KRW',
  'CNY',
  'AUD',
  'CAD',
  'SGD',
  'THB',
  'INR',
] as const;

export const CURRENCY_NAMES: Record<(typeof CURRENCIES)[number], string> = {
  USD: 'United States Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  JPY: 'Japanese Yen',
  PHP: 'Philippine peso',
  KRW: 'South Korean Won',
  CNY: 'Chinese Yuan',
  AUD: 'Australian Dollar',
  CAD: 'Canadian Dollar',
  SGD: 'Singapore Dollar',
  THB: 'Thai Baht',
  INR: 'Indian Rupee',
};

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'fil', label: 'Filipino' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'zh-Hans', label: 'Simplified Chinese' },
  { code: 'zh-Hant', label: 'Traditional Chinese' },
  { code: 'es', label: 'Spanish' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
] as const;

export const COUNTRIES = [
  { code: 'PH', label: 'Philippines' },
  { code: 'JP', label: 'Japan' },
  { code: 'KR', label: 'South Korea' },
  { code: 'US', label: 'United States' },
  { code: 'GB', label: 'United Kingdom' },
  { code: 'AU', label: 'Australia' },
  { code: 'SG', label: 'Singapore' },
  { code: 'TH', label: 'Thailand' },
  { code: 'VN', label: 'Vietnam' },
  { code: 'ID', label: 'Indonesia' },
  { code: 'MY', label: 'Malaysia' },
  { code: 'CN', label: 'China' },
  { code: 'TW', label: 'Taiwan' },
  { code: 'HK', label: 'Hong Kong' },
  { code: 'MO', label: 'Macao' },
  { code: 'FR', label: 'France' },
  { code: 'DE', label: 'Germany' },
  { code: 'ES', label: 'Spain' },
  { code: 'IT', label: 'Italy' },
  { code: 'NL', label: 'Netherlands' },
  { code: 'BE', label: 'Belgium' },
  { code: 'AT', label: 'Austria' },
  { code: 'PT', label: 'Portugal' },
  { code: 'IE', label: 'Ireland' },
  { code: 'CH', label: 'Switzerland' },
  { code: 'SE', label: 'Sweden' },
  { code: 'NO', label: 'Norway' },
  { code: 'DK', label: 'Denmark' },
  { code: 'FI', label: 'Finland' },
  { code: 'PL', label: 'Poland' },
  { code: 'CZ', label: 'Czechia' },
  { code: 'HU', label: 'Hungary' },
  { code: 'RO', label: 'Romania' },
  { code: 'BG', label: 'Bulgaria' },
  { code: 'HR', label: 'Croatia' },
  { code: 'RS', label: 'Serbia' },
  { code: 'GR', label: 'Greece' },
  { code: 'IS', label: 'Iceland' },
  { code: 'CA', label: 'Canada' },
  { code: 'NZ', label: 'New Zealand' },
  { code: 'MX', label: 'Mexico' },
  { code: 'BR', label: 'Brazil' },
  { code: 'AR', label: 'Argentina' },
  { code: 'CL', label: 'Chile' },
  { code: 'CO', label: 'Colombia' },
  { code: 'PE', label: 'Peru' },
  { code: 'IN', label: 'India' },
  { code: 'PK', label: 'Pakistan' },
  { code: 'BD', label: 'Bangladesh' },
  { code: 'LK', label: 'Sri Lanka' },
  { code: 'NP', label: 'Nepal' },
  { code: 'KH', label: 'Cambodia' },
  { code: 'LA', label: 'Laos' },
  { code: 'MM', label: 'Myanmar' },
  { code: 'AE', label: 'United Arab Emirates' },
  { code: 'SA', label: 'Saudi Arabia' },
  { code: 'QA', label: 'Qatar' },
  { code: 'KW', label: 'Kuwait' },
  { code: 'BH', label: 'Bahrain' },
  { code: 'OM', label: 'Oman' },
  { code: 'JO', label: 'Jordan' },
  { code: 'IL', label: 'Israel' },
  { code: 'TR', label: 'Turkey' },
  { code: 'EG', label: 'Egypt' },
  { code: 'ZA', label: 'South Africa' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'KE', label: 'Kenya' },
  { code: 'RU', label: 'Russia' },
  { code: 'UA', label: 'Ukraine' },
] as const;

/** Default currency when a home country is selected. */
export const COUNTRY_CURRENCY: Record<string, string> = {
  PH: 'PHP',
  JP: 'JPY',
  KR: 'KRW',
  US: 'USD',
  GB: 'GBP',
  AU: 'AUD',
  SG: 'SGD',
  TH: 'THB',
  VN: 'VND',
  ID: 'IDR',
  MY: 'MYR',
  CN: 'CNY',
  TW: 'TWD',
  HK: 'HKD',
  MO: 'MOP',
  FR: 'EUR',
  DE: 'EUR',
  ES: 'EUR',
  IT: 'EUR',
  NL: 'EUR',
  BE: 'EUR',
  AT: 'EUR',
  PT: 'EUR',
  IE: 'EUR',
  FI: 'EUR',
  GR: 'EUR',
  HR: 'EUR',
  CH: 'CHF',
  SE: 'SEK',
  NO: 'NOK',
  DK: 'DKK',
  PL: 'PLN',
  CZ: 'CZK',
  HU: 'HUF',
  RO: 'RON',
  BG: 'BGN',
  RS: 'RSD',
  IS: 'ISK',
  CA: 'CAD',
  NZ: 'NZD',
  MX: 'MXN',
  BR: 'BRL',
  AR: 'ARS',
  CL: 'CLP',
  CO: 'COP',
  PE: 'PEN',
  IN: 'INR',
  PK: 'PKR',
  BD: 'BDT',
  LK: 'LKR',
  NP: 'NPR',
  KH: 'KHR',
  LA: 'LAK',
  MM: 'MMK',
  AE: 'AED',
  SA: 'SAR',
  QA: 'QAR',
  KW: 'KWD',
  BH: 'BHD',
  OM: 'OMR',
  JO: 'JOD',
  IL: 'ILS',
  TR: 'TRY',
  EG: 'EGP',
  ZA: 'ZAR',
  NG: 'NGN',
  KE: 'KES',
  RU: 'RUB',
  UA: 'UAH',
};

export function labelize(value: string): string {
  return value
    .replace(/[_-]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join(' ');
}
